Repository Team-Lecue/Lecue-Client, pull requests merged in 2024-01, with the labels that each got.

#4 [Init] React-Query 초기 세팅
  .github/pull_request_template.md
  package.json
  src/App.tsx
  yarn.lock
Labels: init

#5 init: Global 스타일 적용, 폴더 구조 수정
  src/App.tsx
  src/assets/icon/.keep
  src/assets/icon/svgs/.keep
  src/libs/hooks/.keep
  src/main.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
Labels: init

#9 [Init] 초기세팅 - Theme, Issue Template, README.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  .prettierrc
  README.md
  index.html
  src/App.tsx
  src/Router.tsx
  src/styles/GlobalStyles.ts
  src/styles/emotion.d.ts
  src/styles/fonts/SequelSansMediumOblBody.woff
  src/styles/theme.ts
  vite.config.ts
Labels: ⚙️init, 🐬도리

#11 [Init] svg 초기세팅
  package.json
  src/assets/icon/svgs/ic_arrow_left.svg
  src/assets/icon/svgs/ic_btn_floating_list.svg
  src/assets/icon/svgs/ic_btn_floating_postit.svg
  src/assets/icon/svgs/ic_btn_floating_sticker.svg
  src/assets/icon/svgs/ic_btn_floating_write.svg
  src/assets/icon/svgs/ic_crown.svg
  src/assets/icon/svgs/ic_date.svg
  src/assets/icon/svgs/ic_home.svg
  src/assets/icon/svgs/ic_notice.svg
  src/assets/icon/svgs/ic_sharing.svg
  src/assets/icon/svgs/index.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ⚙️init, 🦭쩡우

#16 [ Common ] 공통 Header 컴포넌트 구현
  src/assets/index.ts
  src/components/.gitkeep
  src/components/common/Header/Header.style.ts
  src/components/common/Header/index.tsx
Labels: 💡feat, 🦭쩡우

#23 [ Common ] 디자인 시스템 추가 반영
  src/assets/icon/ic_camera.svg
  src/assets/img/img_book.svg
  src/assets/img/img_star_orangeline.svg
  src/assets/img/img_star_postit.svg
  src/assets/index.ts
  src/components/common/Header/Header.style.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: ⚙️init

#21 [ StickerPack ] 뷰 구현
  .stylelintrc.json
  package.json
  src/Router.tsx
  src/StickerPack/components/.gitkeep
  src/StickerPack/components/StickerList/StickerList.style.ts
  src/StickerPack/components/StickerList/index.tsx
  src/StickerPack/page/StickerPack.style.ts
  src/StickerPack/page/StickerPack.tsx
  src/StickerPack/page/StickerPack/StickerPack.style.ts
  src/StickerPack/page/StickerPack/index.tsx
  yarn.lock
Labels: 💡feat, 🪼비니

#24 [ DetailPage ] 롤링페이퍼 상세 뷰 상단 축하글 UI 퍼블리싱
  index.html
  src/Detail/components/.gitkeep
  src/Detail/components/BookInfoBox/BookInfoBox.style.ts
  src/Detail/components/BookInfoBox/index.tsx
  src/Detail/components/BookInfoContainer/index.tsx
  src/Detail/components/SlideBanner/SlideBanner.style.ts
  src/Detail/components/SlideBanner/index.tsx
  src/Detail/components/SlideBannerItem/SlideBannerItem.style.ts
  src/Detail/components/SlideBannerItem/index.tsx
  src/Detail/constants/.gitkeep
  src/Detail/hooks/.gitkeep
  src/Detail/page/DetailPage/index.tsx
  src/Router.tsx
  src/assets/icon/ic_crown.svg
  src/assets/icon/ic_date.svg
  src/assets/index.ts
  src/styles/GlobalStyles.ts
  src/styles/fonts/SequelSansMediumOblBody.woff
  src/styles/theme.ts
Labels: 💡feat, 🦭쩡우

#57 [ common ] axios 세팅
  package.json
  src/libs/api.ts
  yarn.lock
Labels: ⚙️init, 🪼비니

#54 [ Home ] 홈 뷰 퍼블리싱
  .github/workflows/CD.yml
  deploy/Dockerfile
  package.json
  src/App.tsx
  src/Home/components/.gitkeep
  src/Home/components/LecueBookList/LecueBookList.style.ts
  src/Home/components/LecueBookList/index.tsx
  src/Home/components/NavigateLecueBook/NavigateLecueBook.style.ts
  src/Home/components/NavigateLecueBook/index.tsx
  src/Home/page/Home.style.ts
  src/Home/page/HomePage.tsx
  src/Home/page/index.tsx
  src/Router.tsx
  src/components/common/Header/index.tsx
  src/libs/api.ts
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
  yarn.lock
Labels: 💡feat, 🐬도리

#61 [ StickerPack ] 스티커팩 API 패칭
  src/StickerPack/api/getStickerPack.ts
  src/StickerPack/components/StickerList/StickerList.style.ts
  src/StickerPack/components/StickerList/index.tsx
  src/StickerPack/hooks/.gitkeep
  src/StickerPack/hooks/useGetStickerPack.ts
  src/StickerPack/page/StickerPack/StickerPack.style.ts
  src/StickerPack/page/StickerPack/index.tsx
  src/StickerPack/type/stickerPackType.ts
Labels: 💡feat, 🪼비니

#59 [ DetailPage ] 레큐노트 지그재그 뷰 UI 퍼블리싱
  src/Detail/components/BookInfoContainer/index.tsx
  src/Detail/components/LecueNoteLIstHeader/LecueNoteListHeader.style.ts
  src/Detail/components/LecueNoteLIstHeader/index.tsx
  src/Detail/components/LecueNoteListContainer/LecueNoteListContainer.style.ts
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/components/SlideBanner/SlideBanner.style.ts
  src/Detail/components/SlideBannerItem/SlideBannerItem.style.ts
  src/Detail/components/SlideBannerItem/index.tsx
  src/Detail/components/SmallLecueNote/SmallLecueNote.style.ts
  src/Detail/components/SmallLecueNote/index.tsx
  src/Detail/components/ZigZagView/ZigZagView.style.ts
  src/Detail/components/ZigZagView/index.tsx
  src/Detail/page/DetailPage/DetailPage.style.ts
  src/Detail/page/DetailPage/index.tsx
  src/assets/button/btn_floating_list.svg
  src/assets/button/btn_floating_postit.svg
  src/assets/icon/ic_camera.svg
  src/assets/img/img_book.svg
  src/assets/img/img_star_orangeline.svg
  src/assets/img/img_star_postit.svg
  src/assets/index.ts
  src/components/common/Header/Header.style.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: 💡feat, 🦭쩡우

#60 [ Login ] 카카오 로그인 뷰 퍼블리싱
  .github/workflows/CD.yml
  deploy/Dockerfile
  package.json
  src/App.tsx
  src/Login/components/Comment/Comment.style.ts
  src/Login/components/Comment/index.tsx
  src/Login/components/Header/Header.style.ts
  src/Login/components/Header/index.tsx
  src/Login/components/LecueLogo/LecueLogo.style.ts
  src/Login/components/LecueLogo/index.tsx
  src/Login/components/LoginBtnContainer/LoginBtnContainer.style.ts
  src/Login/components/LoginBtnContainer/index.tsx
  src/Login/constants/.gitkeep
  src/Login/hooks/.gitkeep
  src/Login/page/Login.style.ts
  src/Login/page/index.tsx
  src/Router.tsx
  src/assets/button/btn_kakaologin.svg
  src/assets/img/img_kakao_01.svg
  src/assets/img/img_kakao_02.svg
  src/assets/img/img_kakao_03.svg
  src/assets/img/img_kakao_book.svg
  src/assets/img/img_kakao_logo.svg
  src/assets/img/img_kakao_spring.svg
  src/assets/img/img_kakao_star_orange.svg
  src/assets/img/img_kakao_star_white.svg
  src/assets/index.ts
  src/components/common/Header/index.tsx
  src/libs/api.ts
  src/styles/GlobalStyles.ts
  yarn.lock
Labels: 💡feat, 🐬도리

#69 [ DetailPage ] 레큐노트 리스트 선형 뷰 UI 퍼블리싱
  index.html
  src/Detail/components/BigLecueNote/BigLecueNote.style.ts
  src/Detail/components/BigLecueNote/index.tsx
  src/Detail/components/BookInfoBox/BookInfoBox.style.ts
  src/Detail/components/LecueNoteListContainer/LecueNoteListContainer.style.ts
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/components/LecueNoteModal/LecueNoteModal.style.ts
  src/Detail/components/LecueNoteModal/index.tsx
  src/Detail/components/LinearView/LinearView.style.ts
  src/Detail/components/LinearView/index.tsx
  src/Detail/components/SlideBanner/SlideBanner.style.ts
  src/Detail/components/SmallLecueNote/SmallLecueNote.style.ts
  src/Detail/components/SmallLecueNote/index.tsx
  src/Detail/components/ZigZagView/ZigZagView.style.ts
  src/Detail/components/ZigZagView/index.tsx
  src/Detail/page/DetailPage/DetailPage.style.ts
  src/Detail/page/DetailPage/index.tsx
  src/assets/button/btn_floating_sticker_orange.svg
  src/assets/button/btn_floating_write_orange.svg
  src/assets/icon/ic_x.svg
  src/assets/index.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: 💡feat, 🦭쩡우, 🖼️ publish

#70 [ StickerPack ] 선택된 스티커 데이터 라우트 이동
  src/StickerPack/components/StickerList/index.tsx
  src/StickerPack/page/StickerPack/StickerPack.style.ts
  src/StickerPack/page/StickerPack/index.tsx
  src/StickerPack/type/stickerPackType.ts
Labels: 💡feat, 🪼비니

#62 [Splash] 스플래시 뷰 퍼블리싱
  package.json
  src/Router.tsx
  src/Splash/component/Body/Body.style.ts
  src/Splash/component/Body/index.tsx
  src/Splash/component/Bottom/Bottom.style.ts
  src/Splash/component/Bottom/index.tsx
  src/Splash/component/Header/Header.style.ts
  src/Splash/component/Header/index.tsx
  src/Splash/page/SplashPage/SplashPage.style.ts
  src/Splash/page/SplashPage/index.tsx
  src/assets/img/img_splash_logo.svg
  src/assets/index.ts
  yarn.lock
Labels: 🐠아루밍, 🖼️ publish

#73 [ CreateNote ] 뷰 퍼블리싱
  src/LecueNote/components/CreateNote/CreateNote.style.ts
  src/LecueNote/components/CreateNote/index.tsx
  src/LecueNote/components/Footer/Footer.style.ts
  src/LecueNote/components/Footer/index.tsx
  src/LecueNote/components/SelectColor/SelectColor.style.ts
  src/LecueNote/components/SelectColor/index.tsx
  src/LecueNote/components/ShowColorChart/ShowColorChart.style.ts
  src/LecueNote/components/ShowColorChart/index.tsx
  src/LecueNote/components/WriteNote/WriteNote.style.ts
  src/LecueNote/components/WriteNote/index.tsx
  src/LecueNote/constants/colorChart.ts
  src/LecueNote/page/LeceuNotePage/LecueNotePage.style.ts
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/LecueNote/type/lecueNoteType.ts
  src/Router.tsx
  src/styles/GlobalStyles.ts
Labels: 🐠아루밍, 🖼️ publish

#66 [ Register ] 닉네임 설정 뷰 퍼블리싱
  src/Register/components/NicknameInput/NicknameInput.style.ts
  src/Register/components/NicknameInput/index.tsx
  src/Register/components/RegisterLogo/RegisterLogo.style.ts
  src/Register/components/RegisterLogo/index.tsx
  src/Register/components/SubmitButton/SubmitButton.style.ts
  src/Register/components/SubmitButton/index.tsx
  src/Register/constants/.gitkeep
  src/Register/hooks/.gitkeep
  src/Register/page/Register.style.ts
  src/Register/page/index.tsx
  src/Router.tsx
Labels: 💡feat, 🐬도리, 🖼️ publish

#81 [ CreateNote] 레큐 노트 내부 기능 구현
  src/LecueNote/components/CreateNote/CreateNote.style.ts
  src/LecueNote/components/CreateNote/index.tsx
  src/LecueNote/components/Footer/index.tsx
  src/LecueNote/components/SelectColor/SelectColor.style.ts
  src/LecueNote/components/SelectColor/index.tsx
  src/LecueNote/components/ShowColorChart/ShowColorChart.style.ts
  src/LecueNote/components/ShowColorChart/index.tsx
  src/LecueNote/components/WriteNote/WriteNote.style.ts
  src/LecueNote/components/WriteNote/index.tsx
  src/LecueNote/page/LeceuNotePage/LecueNotePage.style.ts
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/LecueNote/type/lecueNoteType.ts
  src/assets/icon/ic_camera_small.svg
  src/assets/index.ts
Labels: 💡feat, 🐠아루밍

#87 [ Common ] 공통모달 구현
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/assets/img/img_modal_ex.svg
  src/assets/index.ts
  src/components/common/Modal/CommonModal.tsx
  src/components/common/Modal/CommonModalForm/CommonModalForm.style.ts
  src/components/common/Modal/CommonModalForm/index.tsx
  src/components/common/Modal/ModalPortal.tsx
  src/components/common/Modal/constants/ModalContents.tsx
Labels: 💡feat, 🐠아루밍, 🖼️ publish

#82 [ Mypage ] 마이페이지 퍼블리싱
  src/Mypage/components/LecueBook/LecueBook.style.ts
  src/Mypage/components/LecueBook/index.tsx
  src/Mypage/components/LecueList/LecueList.style.ts
  src/Mypage/components/LecueList/index.tsx
  src/Mypage/components/LecueNote/LecueNote.style.ts
  src/Mypage/components/LecueNote/index.tsx
  src/Mypage/components/Nickname/Nickname.style.ts
  src/Mypage/components/Nickname/index.tsx
  src/Mypage/constants/DATA.ts
  src/Mypage/hooks/.gitkeep
  src/Mypage/page/Mypage.style.ts
  src/Mypage/page/index.tsx
  src/Mypage/types/myPageType.ts
  src/Router.tsx
  src/assets/icon/ic_waste.svg
  src/assets/index.ts
Labels: 💡feat, 🐬도리, 🖼️ publish

#94 [ CreateNote ] 이미지 업로드 기능 구현
  src/LecueNote/components/CreateNote/index.tsx
  src/LecueNote/components/SelectColor/index.tsx
  src/LecueNote/components/ShowColorChart/ShowColorChart.style.ts
  src/LecueNote/components/ShowColorChart/index.tsx
  src/LecueNote/components/WriteNote/WriteNote.style.ts
  src/LecueNote/components/WriteNote/index.tsx
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/LecueNote/type/lecueNoteType.ts
Labels: 💡feat, 🐠아루밍

#92 [ Mypage ] 레큐노트 배경색상, 텍스트색상 적용
  src/Mypage/components/LecueList/LecueList.style.ts
  src/Mypage/components/LecueList/index.tsx
  src/Mypage/components/LecueNote/LecueNote.style.ts
  src/Mypage/components/LecueNote/index.tsx
  src/Mypage/constants/DATA.ts
  src/Mypage/types/myPageType.ts
Labels: 💡feat, 🐬도리

#91 [ SelectBook ] 레큐북 생성 요금 설정 페이지 UI 퍼블리싱
  src/Router.tsx
  src/SelectBook/components/BookTypeBox/BookTypeBox.style.ts
  src/SelectBook/components/BookTypeBox/index.tsx
  src/SelectBook/components/BookTypeBoxOption/BookTypeBoxOption.style.ts
  src/SelectBook/components/BookTypeBoxOption/index.tsx
  src/SelectBook/components/CompleteButton/CompleteButton.style.ts
  src/SelectBook/components/CompleteButton/index.tsx
  src/SelectBook/components/MakeLecueBookButton/MakeLecueBookButton.style.ts
  src/SelectBook/components/MakeLecueBookButton/index.tsx
  src/SelectBook/constants/.gitkeep
  src/SelectBook/hooks/.gitkeep
  src/SelectBook/page/SelectBookPage/SelectBookPage.style.ts
  src/SelectBook/page/SelectBookPage/index.tsx
  src/assets/icon/ic_check.svg
  src/assets/img/img_book_backgray.svg
  src/assets/img/img_book_orange.svg
  src/assets/img/img_book_orange_big.svg
  src/assets/img/img_event.svg
  src/assets/img/img_saleprice.svg
  src/assets/index.ts
Labels: 🦭쩡우, 🖼️ publish

#90 [ Detail ] 데이터 패칭
  src/Detail/api/getBookDetail.ts
  src/Detail/components/.gitkeep
  src/Detail/components/BookInfoBox/index.tsx
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/components/LinearView/index.tsx
  src/Detail/components/ZigZagView/ZigZagView.style.ts
  src/Detail/components/ZigZagView/index.tsx
  src/Detail/hooks/.gitkeep
  src/Detail/hooks/useGetBookDetail.ts
  src/Detail/page/DetailPage/index.tsx
  src/Detail/type/lecueBookType.ts
Labels: 📝chore, 🪼비니

#86 [ StcikerAttach ] 스티커 부착 페이지
  package.json
  src/Detail/api/getBookDetail.ts
  src/Detail/components/BookInfoBox/index.tsx
  src/Detail/components/LecueNoteListContainer/LecueNoteListContainer.style.ts
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/components/LinearView/index.tsx
  src/Detail/components/ZigZagView/ZigZagView.style.ts
  src/Detail/components/ZigZagView/index.tsx
  src/Detail/hooks/useGetBookDetail.ts
  src/Detail/page/DetailPage/DetailPage.style.ts
  src/Detail/page/DetailPage/index.tsx
  src/Detail/type/lecueBookType.ts
  src/Router.tsx
  src/StickerAttach/components/.gitkeep
  src/StickerAttach/constants/.gitkeep
  src/StickerAttach/hooks/.gitkeep
  src/StickerAttach/page/StickerAttach.style.ts
  src/StickerAttach/page/index.tsx
  src/StickerPack/page/StickerPack/index.tsx
  src/assets/icon/ic_caution.svg
  src/assets/index.ts
  yarn.lock
Labels: 💡feat, 🪼비니

#100 [ Mypage ] 레큐북, 레큐노트 클릭 이벤트
  src/Mypage/components/LecueBook/index.tsx
  src/Mypage/components/LecueList/index.tsx
  src/Mypage/components/LecueNote/index.tsx
  src/Mypage/types/myPageType.ts
Labels: 💡feat, 🐬도리

#104 [TargetPage] 레큐북 생성 Presigned URL 연동
  src/Target/components/FavoriteImageInput/index.tsx
  src/Target/page/TargetPage/index.tsx
  src/Target/util/api.ts
Labels: 🦭쩡우, 🚀api

#115 [ StickerAttach ] 수정된 스타일 필드 반영
  src/Detail/components/BigLecueNote/BigLecueNote.style.ts
  src/Detail/components/BigLecueNote/index.tsx
  src/Detail/components/BookInfoBox/BookInfoBox.style.ts
  src/Detail/components/BookInfoBox/index.tsx
  src/Detail/components/LecueNoteLIstHeader/LecueNoteListHeader.style.ts
  src/Detail/components/LecueNoteLIstHeader/index.tsx
  src/Detail/components/LecueNoteListContainer/LecueNoteListContainer.style.ts
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/components/SmallLecueNote/SmallLecueNote.style.ts
  src/Detail/components/SmallLecueNote/index.tsx
  src/Detail/type/lecueBookType.ts
  src/StickerAttach/api/postStickerState.ts
Labels: 💄style, 🪼비니

#110 [ Home ] api 연결
  src/Home/api/getLecueBook.ts
  src/Home/components/LecueBookList/LecueBookList.style.ts
  src/Home/components/LecueBookList/index.tsx
  src/Home/hooks/useGetLecueBook.ts
Labels: 🐠아루밍, 🚀api

#122 [ StickerAttach ] 데이터 패칭
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/components/ZigZagView/ZigZagView.style.ts
  src/StickerAttach/api/postStickerState.ts
  src/StickerAttach/hooks/.gitkeep
  src/StickerAttach/hooks/usePostStickerState.ts
  src/StickerAttach/type/postStickerType.ts
Labels: 💡feat, 🪼비니

#124 [ StickerAttach ] 스크롤 위치 복원 + 버그 픽스
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/components/ZigZagView/ZigZagView.style.ts
  src/Detail/components/ZigZagView/index.tsx
  src/Detail/page/DetailPage/index.tsx
  src/StickerAttach/hooks/usePostStickerState.ts
Labels: 💄style

#125 [ Home ] 라우팅
  src/Home/components/LecueBookList/index.tsx
  src/Home/components/NavigateLecueBook/NavigateLecueBook.style.ts
  src/Home/components/NavigateLecueBook/index.tsx
  src/Home/page/Home.style.ts
  src/Home/page/index.tsx
  src/Router.tsx
  src/Splash/component/Body/Body.style.ts
  src/Splash/component/Bottom/Bottom.style.ts
  src/Splash/component/Bottom/index.tsx
  src/Splash/component/Header/Header.style.ts
  src/Splash/page/SplashPage/SplashPage.style.ts
  src/Splash/page/SplashPage/index.tsx
Labels: 💡feat, 🐠아루밍

#119 [ Login ] 로그인/회원가입 API 연결하기
  src/Login/api/getLoginToken.ts
  src/Login/api/oAuth.ts
  src/Login/api/postLoginToken.ts
  src/Login/components/LoginBtnContainer/index.tsx
  src/Login/components/LoginCallback/LoginCallback.tsx
  src/Register/components/NicknameInput/index.tsx
  src/Register/components/SubmitButton/index.tsx
  src/Register/page/index.tsx
  src/Router.tsx
  src/main.tsx
Labels: 🐬도리, 🚀api

#136 [ CreateNote ] presigned url put 통신위치 변경
  src/LecueNote/components/CreateNote/index.tsx
  src/LecueNote/components/Footer/index.tsx
  src/LecueNote/components/SelectColor/index.tsx
  src/LecueNote/components/ShowColorChart/index.tsx
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/LecueNote/type/lecueNoteType.ts
Labels: 🛠️refactor, 🐠아루밍

#140 [ DetailPage ] Modal X 버튼 클릭 시 삭제 Event 바인딩 오류 FIX
  src/Detail/components/LecueNoteModal/index.tsx
  src/Detail/components/SmallLecueNote/index.tsx
  vite.config.ts
Labels: 🐞fix, 🦭쩡우

#139 [ StickerPack ] 로그인 분기 처리
  src/StickerPack/api/getStickerPack.ts
  src/StickerPack/page/StickerPack/index.tsx
Labels: 🪼비니, 🚀api

#144 [ Common ] Error View 구현
  src/Router.tsx
  src/assets/img/img_error.svg
  src/assets/index.ts
  src/components/common/ErrorPage/ErrorPage.style.ts
  src/components/common/ErrorPage/index.tsx
Labels: 🦭쩡우, 🖼️ publish

#143 [ StickerAttach ] 스티커 위치 바닥으로부터 잡기
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/components/LecueNoteModal/LecueNoteModal.style.ts
  src/Detail/components/ZigZagView/index.tsx
  src/StickerPack/components/StickerList/index.tsx
Labels: 🐞fix, 🪼비니

#146 [ myPage ] API 패칭
  src/Mypage/api/getMyBookList.ts
  src/Mypage/api/getMyNickName.ts
  src/Mypage/api/getMyNoteList.ts
  src/Mypage/components/LecueBook/index.tsx
  src/Mypage/components/LecueList/index.tsx
  src/Mypage/components/LecueNote/index.tsx
  src/Mypage/components/Nickname/index.tsx
  src/Mypage/components/NoteModal/NoteModal.style.ts
  src/Mypage/components/NoteModal/index.tsx
  src/Mypage/hooks/useGetMyBookList.ts
  src/Mypage/hooks/useGetMyNickname.ts
  src/Mypage/hooks/useGetMyNoteList.ts
  src/Mypage/types/myPageType.ts
Labels: 🪼비니, 🚀api

#156 [ Mypage ] 레큐북 삭제 구현
  src/Mypage/api/deleteMyBook.ts
  src/Mypage/components/LecueBook/index.tsx
  src/Mypage/components/NoteModal/index.tsx
  src/Mypage/hooks/.gitkeep
  src/Mypage/hooks/useDeleteMyBook.ts
Labels: 🪼비니, 🚀api

#151 [DetailPage] 레큐노트 0개일 때 뷰 컴포넌트 구현
  src/Detail/components/EmptyView/EmptyView.style.ts
  src/Detail/components/EmptyView/index.tsx
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/assets/img/img_empty.svg
  src/assets/index.ts
Labels: 🦭쩡우, 🖼️ publish

#154 [ TargetPage ] React-Query 연결
  src/Target/components/FavoriteImageInput/index.tsx
  src/Target/hooks/useGetPresignedUrl.ts
  src/Target/hooks/usePutPresignedUrl.ts
  src/Target/page/TargetPage/index.tsx
  src/Target/util/api.ts
Labels: 🦭쩡우, 🚀api

#157 [ Common ] 공통 모달 수정 및 전반적인 기능 수정
  src/Home/components/NavigateLecueBook/index.tsx
  src/LecueNote/api/postLecueNote.ts
  src/LecueNote/components/Footer/index.tsx
  src/LecueNote/hooks/usePostLecueNote.ts
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/LecueNote/type/lecueNoteType.ts
  src/assets/img/img_modal_bookcomplete.svg
  src/assets/img/img_modal_bookexit.svg
  src/assets/img/img_modal_ex.svg
  src/assets/img/img_modal_login.svg
  src/assets/img/img_modal_mypagedelete.svg
  src/assets/img/img_modal_notecomplete.svg
  src/assets/img/img_modal_noteexit.svg
  src/assets/index.ts
  src/components/common/Header/index.tsx
  src/components/common/Modal/CommonModal.tsx
  src/components/common/Modal/CommonModalForm/index.tsx
  src/components/common/Modal/constants/ModalContents.tsx
Labels: 💡feat, 🐠아루밍

#166 [ Common ] Loading View 구현
  src/Router.tsx
  src/assets/lottie/spiner 120.json
  src/components/common/LoadingPage/LoadingPage.style.ts
  src/components/common/LoadingPage/index.tsx
Labels: 🦭쩡우, 🖼️ publish

#162 [ Register ] 유저 닉네임 설정 PATCH API 연결하기
  src/Login/components/LoginCallback/LoginCallback.tsx
  src/Login/page/index.tsx
  src/Register/api/patchNickname.ts
  src/Register/components/NicknameInput/NicknameInput.style.ts
  src/Register/components/NicknameInput/index.tsx
  src/Register/components/SubmitButton/index.tsx
  src/Register/hooks/.gitkeep
  src/Register/hooks/usePatchNickname.ts
  src/Register/page/index.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: 🐬도리, 🚀api

#171 [ SplashPage ] api 연결
  src/Splash/api/getNoteNum.ts
  src/Splash/component/Body/index.tsx
  src/Splash/hook/useGetNoteNum.ts
  src/Splash/page/SplashPage/index.tsx
Labels: 🐠아루밍, 🚀api

#174 [ Home ] UI 디자인 수정
  src/Home/components/LecueBookList/LecueBookList.style.ts
  src/Home/components/NavigateLecueBook/NavigateLecueBook.style.ts
Labels: 💄style, 🐬도리

#172 [ Mypage ] 레큐북/레큐노트 0개 뷰 컴포넌트 구현
  src/Mypage/components/EmptyView/EmptyView.style.ts
  src/Mypage/components/EmptyView/index.tsx
  src/Mypage/components/LecueList/LecueList.style.ts
  src/Mypage/components/LecueList/index.tsx
  src/Mypage/components/LecueNote/index.tsx
  src/Mypage/components/NoteModal/index.tsx
  src/Mypage/constants/.gitkeep
  src/Mypage/constants/DATA.ts
Labels: 💡feat, 🐬도리

#177 [ CreateBook ] 공통 Modal 연결
  src/CreateBook/page/index.tsx
  src/components/common/Modal/CommonModalForm/index.tsx
  src/components/common/Modal/constants/ModalContents.tsx
Labels: 💡feat, 🦭쩡우

#182 [ DetailPage ] DetailView height bugfix
  src/Detail/components/LecueNoteListContainer/LecueNoteListContainer.style.ts
Labels: 🐞fix, 🦭쩡우

#188 [ CreateBook ] React-Query 연결
  src/CreateBook/hooks/usePostBook.ts
  src/CreateBook/page/index.tsx
Labels: 🦭쩡우, 🚀api

#192 [Hotfix] refetchOnWindowFocus Error Fix
  src/Detail/hooks/useGetBookDetail.ts
  src/Home/hooks/useGetLecueBook.ts
  src/LecueNote/hooks/useGetPresignedUrl.ts
  src/Mypage/hooks/useGetMyBookList.ts
  src/Mypage/hooks/useGetMyNickname.ts
  src/Mypage/hooks/useGetMyNoteList.ts
  src/Splash/hook/useGetNoteNum.ts
  src/StickerPack/hooks/useGetBookUuid.ts
  src/StickerPack/hooks/useGetStickerPack.ts
  src/Target/hooks/useGetPresignedUrl.ts
Labels: 🐞fix, 🦭쩡우

#193 [ HotFix ] Develop으로 가라!
  src/Detail/components/ZigZagView/ZigZagView.style.ts
  src/Detail/hooks/useGetBookDetail.ts
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/Router.tsx
  src/components/common/ErrorPage/index.tsx
Labels: 🐞fix

#195 [Hotfix] usePostBook Error Fix
  src/CreateBook/hooks/usePostBook.ts
  src/CreateBook/page/index.tsx
Labels: 🐞fix, 🦭쩡우
