Repository Team-Lecue/Lecue-Client, pull requests merged in 2024-04, with the labels that each got.

#285 [ Mypage ] 즐겨찾기 한 레큐북 구현
  src/History/api/getMyFavorite.ts
  src/History/components/MyFavoriteBook/.gitkeep
  src/History/components/MyFavoriteBookList/.gitkeep
  src/History/components/MyFavoriteBookList/MyFavoriteBookList.style.ts
  src/History/components/MyFavoriteBookList/index.tsx
  src/History/hooks/useGetMyFavorite.ts
  src/History/types/historyType.ts
  src/Home/components/LecueBookList/LecueBookList.style.ts
  src/Home/components/LecueBookList/index.tsx
  src/components/common/LecueBook/LecueBook.style.ts
  src/components/common/LecueBook/index.tsx
  src/libs/hooks/useDeleteFavorite.ts
Labels: 💡feat, 🐬도리, 🚀api, 🎀SP1

#287 [ Common ] 레큐 노트를 레터로 명칭 변경
  README.md
  index.html
  src/Detail/components/EmptyView/index.tsx
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/Mypage/components/EmptyView/index.tsx
  src/Mypage/components/LecueList/index.tsx
  src/SelectBook/page/SelectBookPage/index.tsx
  src/Splash/component/Body/index.tsx
  src/components/common/Modal/constants/ModalContents.tsx
Labels: 🎀SP1

#289 [ Mypage ] 로그아웃 구현
  src/Enter/page/index.tsx
Labels: 💡feat, 🐬도리, 🎀SP1

#293 [ Login ] 최애 워딩 변경 반영
  src/Login/page/Login.style.ts
  src/assets/img/img_kakao_01.svg
  src/assets/img/img_kakao_02.svg
  src/assets/img/img_kakao_03.svg
Labels: 📝chore, 💄style, 🐬도리, 🎀SP1

#291 [ Mypage ] 외부 링크 연결
  src/Enter/page/index.tsx
Labels: 📝chore, 🐬도리, 🎀SP1

#296 [ Mypage ] 내기록보기 진입페이지 일러스트 추가
  src/HistoryEnter/page/HistoryEnter.style.ts
  src/HistoryEnter/page/index.tsx
  src/assets/img/img_mypage_favorite_lecuebook.svg
  src/assets/img/img_mypage_letter.svg
  src/assets/img/img_mypage_make_lecuebook.svg
  src/assets/index.ts
Labels: 📝chore, 💄style, 🐬도리, 🎀SP1

#304 [ Home ] 일러스트 추가
  package.json
  src/Home/components/HomeMainBanner/HomeMainBanner.style.ts
  src/Home/components/HomeMainBanner/index.tsx
  src/Home/components/HomeSwiper/HomeSwiper.style.ts
  src/Home/components/HomeSwiper/index.tsx
  src/Home/constants/.gitkeep
  src/Home/constants/HomeIllustArr.tsx
  src/Home/page/index.tsx
  src/assets/img/img_home_01.svg
  src/assets/img/img_home_02.svg
  src/assets/img/img_home_03.svg
  src/assets/index.ts
  yarn.lock
Labels: 💡feat, 🐠아루밍, 🎀SP1

#317 [ Home ] 일러스트 깨지는 이슈 해결
  src/assets/img/img_home_01.svg
Labels: 🐞fix, 🐠아루밍

#318 [ Home ] 마이페이지 아이콘 위치 수정
  src/Home/components/HomeMainBanner/HomeMainBanner.style.ts
Labels: 🐞fix, 💄style, 🐠아루밍

#320 [ TargetPage ] 레큐북 제작 뷰 최애 워딩 수정
  src/Target/components/NameInput/index.tsx
  src/Target/page/TargetPage/index.tsx
Labels: 🐞fix, 🦭쩡우

#323 [ LecueNote ] 윈도우 상에서 노트 위에 스크롤 생기는 이슈 해결
  src/Detail/components/BigLecueNote/BigLecueNote.style.ts
  src/Detail/components/LecueNoteModal/LecueNoteModal.style.ts
  src/LecueNote/components/ShowColorChart/ShowColorChart.style.ts
Labels: 🐞fix, 💄style, 🐠아루밍

#321 [ Mypage ] 내가 만든 레큐북, 즐겨찾기한 레큐북 싱크 안 맞음
  src/History/components/MyLecueBook/index.tsx
  src/History/hooks/useDeleteMyBook.ts
  src/History/hooks/useGetMyBookList.ts
  src/components/common/LecueBook/index.tsx
  src/libs/hooks/useDeleteFavorite.ts
  src/libs/hooks/usePostFavorite.ts
Labels: 🐞fix, 🐬도리

#324 [ Mypage ] 내기록보기 - 사용자가 지정한 배경 / 텍스트 색 반영
  src/History/components/MyLetter/MyLetter.style.ts
  src/History/components/MyLetter/index.tsx
  src/History/types/historyType.ts
Labels: 🐞fix, 🦭쩡우
