Repository Team-Lecue/Lecue-Client, pull requests merged in 2024-06, with the labels that each got.

#338 [ Common ] 엑세스 토큰 관리
  src/CreateBook/utils/api.ts
  src/Detail/api/getBookDetail.ts
  src/Detail/api/getBookDetailLogin.ts
  src/Detail/components/BookInfoBox/index.tsx
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/page/DetailPage/index.tsx
  src/EditNickname/api/patchNickname.ts
  src/EditNickname/components/EditButton/index.tsx
  src/EditNickname/components/NicknameInput/index.tsx
  src/EditNickname/hooks/usePatchNickname.ts
  src/EditNickname/page/index.tsx
  src/EditNickname/types/editNicknameTypes.ts
  src/Enter/page/index.tsx
  src/History/api/deleteMyBook.ts
  src/History/api/getMyBookList.ts
  src/History/api/getMyFavorite.ts
  src/History/api/getMyNoteList.ts
  src/Home/api/getLecueBook.ts
  src/Home/components/HomeMainBanner/index.tsx
  src/Home/page/index.tsx
  src/LecueNote/api/getPresignedUrl.ts
  src/LecueNote/api/postLecueNote.ts
  src/LecueNote/api/putPresignedUrl.ts
  src/LecueNote/components/WriteNote/index.tsx
  src/Login/api/postLoginToken.ts
  src/Login/hooks/usePostLoginToken.ts
  src/Register/api/patchNickname.ts
  src/Register/components/SubmitButton/index.tsx
  src/Register/hooks/usePatchNickname.ts
  src/Register/page/index.tsx
  src/Register/types/registerTypes.ts
  src/SelectView/SelectView.tsx
  src/Splash/api/getNoteNum.ts
  src/StickerAttach/api/postStickerState.ts
  src/StickerPack/api/getBookUuid.ts
  src/StickerPack/api/getStickerPack.ts
  src/Target/util/api.ts
  src/libs/api.ts
  src/libs/api/deleteFavorite.ts
  src/libs/api/getFavorite.ts
  src/libs/api/getMyNickName.ts
  src/libs/api/postFavorite.ts
Labels: 📝chore, 🛠️refactor, 🐬도리

#342 [ Common ] 개발의존성으로 라이브러리 재설치
  package.json
  yarn.lock
Labels: 🛠️refactor, 🐬도리

#340 [ Common ] Axios Instance 반복 생성 개선
  src/libs/api.ts
Labels: 🛠️refactor, 🐬도리

#345 [ Optimization ] 초기 로드 번들 사이즈 및 이미지를 최적화합니다.
  package.json
  src/CreateBook/components/BookInfoSection/BookInfoSection.style.ts
  src/CreateBook/components/BookInfoSection/index.tsx
  src/CreateBook/components/BookInfoTextarea/index.tsx
  src/CreateBook/components/BookInput/index.tsx
  src/CreateBook/components/BookInputSection/BookInputSection.style.ts
  src/CreateBook/components/BookInputSection/index.tsx
  src/CreateBook/components/CompleteButton/CompleteButton.style.ts
  src/CreateBook/components/CompleteButton/index.tsx
  src/CreateBook/components/SelectColor/index.tsx
  src/CreateBook/components/ShowColorChart/index.tsx
  src/CreateBook/page/CreateBook.style.ts
  src/CreateBook/page/index.tsx
  src/CreateBook/type/createBookType.ts
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/components/SmallLecueNote/SmallLecueNote.style.ts
  src/Detail/components/SmallLecueNote/index.tsx
  src/LecueNote/components/WriteNote/NoteLoading/index.tsx
  src/LecueNote/util/handleClickHeicToJpg.ts
  src/Router.tsx
  src/Splash/component/Body/index.tsx
  src/Target/components/CompleteButton/CompleteButton.style.ts
  src/Target/components/CompleteButton/index.tsx
  src/Target/components/FavoriteImageInput/index.tsx
  src/Target/components/FavoriteImageInputSection/FavoriteImageInputSection.style.ts
  src/Target/components/FavoriteImageInputSection/index.tsx
  src/Target/components/NameInputSection/NameInputSection.style.ts
  src/Target/components/NameInputSection/index.tsx
  src/Target/page/TargetPage/TargetPage.style.ts
  src/Target/page/TargetPage/index.tsx
  src/Target/types/targetTypes.ts
  src/assets/lottie/lottie.json
  src/components/common/LoadingPage/index.tsx
  src/styles/GlobalStyles.ts
  yarn.lock
Labels: 🧪optimization
