Repository Team-Lecue/Lecue-Client, pull requests merged in 2024-03, with the labels that each got.

#258 [ Home ] 로그인 여부에 따른 분기처리
  src/Home/page/index.tsx
Labels: 💡feat, 🐠아루밍, 🎀SP1

#257 [ Home ] 바뀐 홈화면 퍼블리싱 (그래픽 제외)
  src/Home/components/LecueBookList/LecueBookList.style.ts
  src/Home/components/LecueBookList/index.tsx
  src/Home/components/NavigateLecueBook/NavigateLecueBook.style.ts
  src/Home/components/NavigateLecueBook/index.tsx
  src/Home/components/NoBookmarkList/NoBookmarkList.style.ts
  src/Home/components/NoBookmarkList/index.tsx
  src/Home/page/index.tsx
  src/assets/icon/ic_alert_o.svg
  src/assets/icon/ic_alert_x.svg
  src/assets/icon/ic_home_favorite.svg
  src/assets/icon/ic_profile.svg
  src/assets/index.ts
Labels: 🐠아루밍, 🖼️ publish, 🎀SP1

#260 [ Home ] 즐겨찾기 아이콘 클릭 시 즐겨찾기에서 삭제
  src/Home/components/LecueBookList/LecueBookList.style.ts
  src/Home/components/LecueBookList/index.tsx
Labels: 💡feat, 🐠아루밍, 🎀SP1

#264 [ Mypage ] Header를 포함한 Mypage 기본 프레임 구현
  src/Mypage/page/Mypage.style.ts
  src/Mypage/page/index.tsx
Labels: 🦭쩡우, 🖼️ publish, 🎀SP1

#267 [ Mypage ] 내 기록보기 진입 페이지 뷰 구현
  src/Mypage/components/HistoryEnterView/HistoryEnterView.style.ts
  src/Mypage/components/HistoryEnterView/index.tsx
Labels: 🐬도리, 🖼️ publish, 🎀SP1

#266 [ Mypage ] 마이페이지 > 진입 페이지 뷰 구현
  src/Mypage/components/Nickname/Nickname.style.ts
  src/Mypage/components/Nickname/index.tsx
  src/Mypage/components/PageLayout/EnterView/EnterView.style.ts
  src/Mypage/components/PageLayout/EnterView/index.tsx
  src/Mypage/components/PageLayout/PageLayout.style.tsx
  src/Mypage/components/PageLayout/index.tsx
  src/Mypage/page/Mypage.style.ts
  src/Mypage/page/index.tsx
  src/Router.tsx
  src/assets/icon/ic_arrow_right_gray.svg
  src/assets/icon/ic_home_favorite_empty.svg
  src/assets/icon/ic_home_favorite_filled.svg
  src/assets/icon/ic_star.svg
  src/assets/icon/ic_star_default.svg
  src/assets/index.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: 🐬도리, 🖼️ publish, 🎀SP1

#269 [ Home ] 즐겨찾기 관련 기능 api 연결
  src/Home/api/getLecueBook.ts
  src/Home/components/LecueBookList/LecueBookList.style.ts
  src/Home/components/LecueBookList/index.tsx
  src/Home/components/NavigateLecueBook/index.tsx
  src/Home/hooks/.gitkeep
  src/Home/hooks/useGetLecueBook.ts
  src/Home/page/index.tsx
  src/libs/api/deleteFavorite.ts
  src/libs/api/getFavorite.ts
  src/libs/hooks/.keep
  src/libs/hooks/useDeleteFavorite.ts
  src/libs/hooks/useGetFavorite.ts
Labels: 🐠아루밍, 🚀api, 🚩리뷰 완료, 🎀SP1

#271 [ Mypage ] 내 기록보기 컴포넌트 전환 모달 구현
  index.html
  src/History/api/.gitkeep
  src/History/components/SelectModal/SelectModal.style.ts
  src/History/components/SelectModal/index.tsx
  src/History/components/SelectModalPortal/index.tsx
  src/History/constants/optionList.ts
  src/History/hooks/.gitkeep
  src/History/page/History.style.ts
  src/History/page/index.tsx
  src/Router.tsx
  src/assets/icon/ic_arrow_down_black.svg
  src/assets/icon/ic_mypage_arrow_right.svg
  src/assets/icon/ic_mypage_touchbar.svg
  src/assets/index.ts
Labels: 💡feat, 🦭쩡우, 🎀SP1

#273 [ Common ] Sentry 설정
  package.json
  src/Router.tsx
  src/components/common/BoundaryErrorPage/index.tsx
  src/main.tsx
  yarn.lock
Labels: 💡feat, 🪼비니, 🎀SP1

#278 [ Mypage ] 마이페이지 조회 (닉네임 GET API) 수정사항 반영
  src/Mypage/api/getMyNickName.ts
Labels: 🐬도리, 🚀api, 🎀SP1

#279 [ Mypage ] 내가 만든 레큐북 구현
  src/Mypage/api/getMyBookList.ts
  src/Mypage/components/MyLecueBook/MyLecueBook.style.ts
  src/Mypage/components/MyLecueBook/index.tsx
  src/Mypage/components/MyLecueBookList/MyLecueBookList.style.ts
  src/Mypage/components/MyLecueBookList/index.tsx
  src/Mypage/components/PageLayout/HistoryEnterView/HistoryEnterView.style.ts
  src/Mypage/components/PageLayout/HistoryEnterView/index.tsx
  src/Mypage/types/myPageType.ts
  src/libs/api/postFavorite.ts
  src/libs/hooks/usePostFavorite.ts
Labels: 💡feat, 🐬도리, 🖼️ publish, 🚀api, 🎀SP1

#283 [ Mypage ] 폴더구조 수정 및 스타일린트 적용
  src/EditNickname/api/.gitkeep
  src/EditNickname/components/.gitkeep
  src/EditNickname/constants/.gitkeep
  src/EditNickname/hooks/.gitkeep
  src/EditNickname/page/EditNickname.style.ts
  src/EditNickname/page/index.tsx
  src/Enter/api/.gitkeep
  src/Enter/components/.gitkeep
  src/Enter/constants/.gitkeep
  src/Enter/hooks/.gitkeep
  src/Enter/page/Enter.style.ts
  src/Enter/page/index.tsx
  src/History/api/deleteMyBook.ts
  src/History/api/getMyBookList.ts
  src/History/api/getMyNoteList.ts
  src/History/components/MyFavoriteBook/.gitkeep
  src/History/components/MyFavoriteBookList/.gitkeep
  src/History/components/MyLecueBook/MyLecueBook.style.ts
  src/History/components/MyLecueBook/index.tsx
  src/History/components/MyLecueBookList/MyLecueBookList.style.ts
  src/History/components/MyLecueBookList/index.tsx
  src/History/hooks/useDeleteMyBook.ts
  src/History/hooks/useGetMyBookList.ts
  src/History/hooks/useGetMyNoteList.ts
  src/History/page/History.style.ts
  src/History/page/index.tsx
  src/History/types/historyType.ts
  src/HistoryEnter/api/.gitkeep
  src/HistoryEnter/components/.gitkeep
  src/HistoryEnter/constants/.gitkeep
  src/HistoryEnter/hooks/.gitkeep
  src/HistoryEnter/page/HistoryEnter.style.ts
  src/HistoryEnter/page/index.tsx
  src/Mypage/api/.gitkeep
  src/Mypage/components/LecueList/LecueList.style.ts
  src/Mypage/components/LecueList/index.tsx
  src/Mypage/components/PageLayout/HistoryEnterView/index.tsx
  src/Mypage/components/PageLayout/index.tsx
  src/Mypage/hooks/.gitkeep
  src/Mypage/page/index.tsx
  src/Mypage/types/myPageType.ts
  src/Router.tsx
  src/assets/icon/ic_arrow_right_gray.svg
  src/assets/index.ts
  src/libs/api/getMyNickName.ts
  src/libs/hooks/useGetMyNickname.ts
Labels: 📝chore, 💄style, 🐬도리, 🎀SP1
