Repository Team-Lecue/Lecue-Client, pull requests merged in 2024-02, with the labels that each got.

#227 [ Common ] 프로덕션 환경으로 배포
  deploy/Dockerfile
  package.json
  vite.config.ts
Labels: 🐞fix, 🪼비니

#228 [ Common ] meta태그 추가. robots.txt 추가
  index.html
  public/.gitkeep
  public/robots.txt
Labels: ⚙️init, 📝chore

#237 [ CreateNote ] 코드 리팩토링 및 최적화
  src/LecueNote/components/CreateNote/CreateNote.style.ts
  src/LecueNote/components/CreateNote/index.tsx
  src/LecueNote/components/SelectColor/index.tsx
  src/LecueNote/components/ShowColorChart/index.tsx
  src/LecueNote/components/WriteNote/index.tsx
  src/LecueNote/hooks/useGetPresignedUrl.ts
  src/LecueNote/page/LeceuNotePage/LecueNotePage.style.ts
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/LecueNote/reducer/lecueNoteReducer.ts
  src/LecueNote/type/lecueNoteType.ts
  src/LecueNote/type/reducerType.ts
Labels: 🐞fix, 🛠️refactor, 🐠아루밍, 🚩리뷰 완료

#225 [ StickerAttach ] hooks 분리
  src/Detail/components/LecueNoteListContainer/LecueNoteListContainer.style.ts
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/hooks/usePostSticker.ts
  src/Detail/hooks/useStickerState.ts
  src/libs/hooks/useAuth.ts
  src/utils/savedScrollPosition.ts
Labels: 🛠️refactor, 🚩리뷰 완료

#233 [ Detail ] Event Bubbling 방지를 위한 코드 구조 수정
  src/Detail/components/LecueNoteModal/index.tsx
  src/Detail/components/SmallLecueNote/index.tsx
Labels: 🛠️refactor, 🦭쩡우, 🚩리뷰 완료

#235 [ Detail ] 사진을 배경으로 하는 레큐 노트 클릭 시, 모달에서 사진 줌되는 이슈
  src/Detail/components/LecueNoteModal/LecueNoteModal.style.ts
Labels: 🐞fix, 🦭쩡우, 🚩리뷰 완료

#239 [ Mypage ] 코드 리팩토링
  src/Mypage/components/EmptyView/index.tsx
  src/Mypage/components/LecueBook/index.tsx
  src/Mypage/components/LecueList/LecueList.style.ts
  src/Mypage/components/LecueList/index.tsx
  src/Mypage/components/LecueNote/index.tsx
  src/Mypage/components/NoteModal/index.tsx
  src/Mypage/types/myPageType.ts
Labels: 🛠️refactor, 🐬도리, 🚩리뷰 완료

#236 [ Register ] 타입 / 닉네임 유효성 검사 로직 분리
  src/Register/components/NicknameInput/index.tsx
  src/Register/components/SubmitButton/index.tsx
  src/Register/hooks/usePatchNickname.ts
  src/Register/page/index.tsx
  src/Register/types/registerTypes.ts
  src/Register/utils/checkInputRange.ts
  src/Register/utils/handleCheckInput.ts
Labels: 🛠️refactor, 🐬도리, 🚩리뷰 완료

#240 [ Login ] LoginCallback 페이지 수정
  src/Login/components/LoginCallback/LoginCallback.tsx
Labels: 🛠️refactor, 🐬도리

#234 [ Login ] React-Query 적용
  src/Login/api/getLoginToken.ts
  src/Login/api/postLoginToken.ts
  src/Login/components/LoginCallback/LoginCallback.tsx
  src/Login/hooks/.gitkeep
  src/Login/hooks/useGetLoginToken.ts
  src/Login/hooks/usePostLoginToken.ts
  src/Register/hooks/usePatchNickname.ts
Labels: 🛠️refactor, 🐬도리, 🚩리뷰 완료

#241 [ StickerAttach ] 스티커 overflow 수정
  src/Detail/components/ZigZagView/ZigZagView.style.ts
Labels: 🐞fix, 🚩리뷰 완료

#251 [ CreateNote ] 이미지 확장자(heic)에 따라 업로드 안되는 이슈 해결
  package.json
  src/LecueNote/components/SelectColor/index.tsx
  src/LecueNote/components/ShowColorChart/index.tsx
  src/LecueNote/components/WriteNote/NoteLoading/NoteLoading.style.ts
  src/LecueNote/components/WriteNote/NoteLoading/index.tsx
  src/LecueNote/components/WriteNote/WriteNote.style.ts
  src/LecueNote/components/WriteNote/index.tsx
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/LecueNote/reducer/lecueNoteReducer.ts
  src/LecueNote/type/lecueNoteType.ts
  src/LecueNote/type/reducerType.ts
  src/LecueNote/util/handleClickFiletoBinary.ts
  src/LecueNote/util/handleClickFiletoString.ts
  src/LecueNote/util/handleClickHeicToJpg.ts
  yarn.lock
Labels: 🐞fix, 🐠아루밍, 🚩리뷰 완료
