Repository Team-Lecue/Lecue-Client, pull requests merged in 2024-05, with the labels that each got.

#333 [ Common ] 코드 리팩토링
  src/App.tsx
  src/History/components/MyLecueBook/index.tsx
  src/History/hooks/useDeleteMyBook.ts
  src/History/hooks/useGetMyBookList.ts
  src/History/hooks/useGetMyFavorite.ts
  src/Home/constants/homeQueryKey.ts
  src/Home/hooks/useGetLecueBook.ts
  src/LecueNote/hooks/usePostLecueNote.ts
  src/LecueNote/hooks/usePutPresignedUrl.ts
  src/LecueNote/page/LeceuNotePage/index.tsx
  src/components/common/LecueBook/index.tsx
  src/constants/queryKeys.ts
  src/libs/hooks/useDeleteFavorite.ts
  src/libs/hooks/useGetFavorite.ts
  src/libs/hooks/useGetMyNickname.ts
  src/libs/hooks/usePostFavorite.ts
Labels: 🛠️refactor, 🐠아루밍

#330 [ Detail ] 즐겨찾기 기능 붙이기
  src/CreateBook/components/BookInput/index.tsx
  src/Detail/api/getBookDetailLogin.ts
  src/Detail/components/BookInfoBox/BookInfoBox.style.ts
  src/Detail/components/BookInfoBox/index.tsx
  src/Detail/hooks/useGetBookDetailLogin.ts
  src/Detail/page/DetailPage/index.tsx
  src/History/components/MyLecueBook/index.tsx
  src/assets/icon/ic_zigzag_star_off.svg
  src/assets/icon/ic_zigzag_star_on.svg
  src/assets/index.ts
  src/libs/hooks/useDeleteFavorite.ts
  src/libs/hooks/usePostFavorite.ts
Labels: 💡feat, 🐬도리, 🚀api

#337 [ Hotfix ] 쿼리 키 싱크 맞추기
  src/Detail/hooks/useGetBookDetailLogin.ts
  src/History/components/MyLecueBook/index.tsx
  src/History/hooks/useDeleteMyBook.ts
  src/History/hooks/useGetMyBookList.ts
  src/History/hooks/useGetMyFavorite.ts
  src/constants/queryKeys.ts
  src/libs/hooks/useDeleteFavorite.ts
  src/libs/hooks/useGetFavorite.ts
  src/libs/hooks/usePostFavorite.ts
Labels: 🐞fix
