Repository Team-Lecue/Lecue-Client, pull requests merged in 2025-01, with the labels that each got.

#353 feat: 레큐북 뷰 초기 진입 시 붉은 박스가 나타났다 사라지는 이슈를 해결합니다.
  src/Detail/components/LecueNoteListContainer/index.tsx
  src/Detail/page/DetailPage/index.tsx
Labels: 🐞fix

#356 [ Hotfix ] 레큐북 뷰 초기 진입 시 스티커 부착 뷰가 렌더링되는 이슈를 수정합니다.
  src/Detail/page/DetailPage/index.tsx
Labels: 🐞fix

#359 [ Home/ Detail ] 레큐 북 즐겨찾기를 여러 번 눌러도 한 번만 추가되게 구현
  src/Detail/components/BookInfoBox/index.tsx
  src/libs/hooks/useDeleteFavorite.ts
  src/libs/hooks/usePostFavorite.ts
Labels: 🛠️refactor, 🐠아루밍

#357 [ Mypage ] 내기록보기 selectOption query parameter로 받아오기
  src/Enter/page/index.tsx
  src/History/components/SelectModal/index.tsx
  src/History/constants/optionList.ts
  src/History/page/index.tsx
  src/History/types/historyType.ts
  src/HistoryEnter/page/index.tsx
  src/Router.tsx
Labels: 🐞fix, 🛠️refactor, 🐬도리
